project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: About.qmd
        text: About
      - href: Projects.qmd
        text: Projects
      - href: Lab.qmd
        text: Lab
      - href: Presentation.qmd
        text: Presentation
      

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

